[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.36", features = ["derive"] }
thiserror = "2.0.12"

[lints.clippy]
needless_return = "allow"
